CREATE TABLE `minions` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL DEFAULT '0',
	`AGE` INT(3) NOT NULL DEFAULT '0',
	`TOWN_ID` INT(11) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
;

CREATE TABLE `towns` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL DEFAULT '0',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
;