CREATE TABLE `people` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL DEFAULT '0',
	`PICTURE` LONGBLOB ,
	`HEIGHT` FLOAT(5) DEFAULT '0',
	`WEIGHT` FLOAT(5) DEFAULT '0',
	`GENDER` CHAR(1) NOT NULL DEFAULT '0',
	`BIRTHDATE` DATETIME(6) NOT NULL ,
	`BIOGRAPHY` TEXT DEFAULT NULL,
	
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
;