<?php

namespace AppBundle\Repository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{

    public function getCar($id)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('c.make', 'c.model', 'c.travelledDistance', 'p.name', 'p.price')
            ->from('AppBundle:Car','c')
            ->innerJoin('c.parts', 'p')
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $qb->getQuery()->execute();
    }
}
