<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $id
     * @return mixed
     */
    public function getCustomerSales($id)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('cm.name', 'count(s.id) as sales', 's.discount', 'sum(p.price)')
            ->from('AppBundle:Customer', 'cm')
            ->join('cm.sales', 's')
            ->join('s.carId', 'c')
            ->join('c.parts', 'p')
            ->where('cm.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $qb->getQuery()->execute();
    }
}
