<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Parts;

/**
 * SupplierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getList($name)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s.id', 's.name', 'count(p.supplierId) as parts')
            ->from('AppBundle:Supplier','s')
            ->leftJoin('s.parts', 'p')
            ->where('p.supplierId = s.id')
            ->where('s.isImporter = :name')
            ->groupBy('p.supplierId')
        ->setParameter('name', $name)
        ->getQuery();

        return $qb->getQuery()->execute();
    }

}
